periodics:
- interval: 40m
  agent: kubernetes
  name: newecho-test
  spec:
    containers:
    - image: alpine
      command: ["/bin/date"]

postsubmits:
  zulfilee/circle2:
  - name: release-postsubmit
    agent: kubernetes
    spec:
      containers:
      - image: alpine
        env:
        - name: workflow_chart
          value: release_workflow
        command: ["/bin/ls"]
    max_concurrency: 10   # Run no more than this number concurrently.
    branches:             # Only run against these branches.
    - master

presubmits:
  zulfilee/circle2:
  - name: release-presubmit
    always_run: true 
    agent: kubernetes
    spec:
      containers:
      - image: alpine
        env:
        - name: workflow_chart
          value: release_workflow
        command: ["ps"]
